name: razorpay_web
description: Flutter plugin for Razorpay SDK. Supports Android, iOS, Web, Windows, Linux, and macOS.
version: 3.1.3

homepage: https://github.com/gauravmehta13/razorpay_web

screenshots:
 - description: 'Example of web payment using Razorpay.'
   path: screenshots/1.jpg
   
environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  eventify: ^1.0.1
  package_info_plus: ^9.0.0
  universal_platform: ^1.1.0
  web: ^1.1.1
  flutter_inappwebview: ^6.2.0-beta.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.26.3
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
        android:
            package: com.razorpay.razorpay_flutter
            pluginClass: RazorpayFlutterPlugin
        ios:
            pluginClass: RazorpayFlutterPlugin
        web:
            pluginClass: RazorpayFlutterPlugin
            fileName: razorpay_flutter_web.dart
        windows:
            dartPluginClass: RazorpayFlutterWebView
        linux:
            dartPluginClass: RazorpayFlutterWebView
        macos:
            dartPluginClass: RazorpayFlutterWebView

